name: "✨ Feature Request"
description: Suggest a new idea or enhancement.
labels: [enhancement]
assignees: []
body:
  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which part of the MCP Hub should this feature be added to?
      options:
        - adif-mcp (Log Validator)
        - wspr-mcp (Propagation Research)
        - qrz-mcp (Callbook Lookup)
        - hub-infrastructure (Global Docs/Actions)
        - new-silo-proposal (Idea for a new tool)
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Feature Description
      description: A clear and concise description of the new feature.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why Is This Needed?
      description: Explain the motivation or problem it solves.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you looked at other ways to solve this?
