name: ci-adif-mcp

on:
  push:
    branches: [ main ]
    paths:
      - 'adif-mcp/**'
      - '.github/workflows/ci.yml'
      - '.github/scripts/validate_manifest.py'
  pull_request:
    paths:
      - 'adif-mcp/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    # Ensures all 'run' steps happen inside the silo folder
    defaults:
      run:
        working-directory: ./adif-mcp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git describe/tags logic

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Sync deps
        run: |
          set -e
          if [ -f uv.lock ]; then
            uv sync --frozen
          else
            uv sync
          fi

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Type-check (mypy)
        run: uv run mypy src

      - name: Tests (pytest)
        run: uv run pytest -q

      - name: Manifest validate (CLI Tool)
        run: uv run adif-mcp validate-manifest

      - name: Manifest validate (Global Script)
        # Use the updated script from the hub root
        run: python3 ../.github/scripts/validate_manifest.py .

      - name: Read project version
        id: pj
        # Running cz inside the silo directory
        run: echo "version=$(uv run cz version --project)" >> "$GITHUB_OUTPUT"

      - name: Read latest git tag
        id: tag
        working-directory: . # Check tags at the hub level
        run: echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo none)" >> "$GITHUB_OUTPUT"

      - name: Enforce pyproject == latest tag
        if: steps.tag.outputs.tag != 'none'
        run: |
          PJ="v${{ steps.pj.outputs.version }}"
          TG="${{ steps.tag.outputs.tag }}"
          echo "pyproject: ${PJ}"
          echo "latest tag: ${TG}"
          test "$PJ" = "$TG" || { echo "::error ::Version mismatch: Silo version must match Hub tag"; exit 1; }