name: release-adif-mcp

on:
  push:
    tags:
      - "v*" # Triggered by global hub tags

jobs:
  build:
    name: Build sdist+wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./adif-mcp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essential for version/tag comparison

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Sync deps
        run: uv sync --frozen

      - name: Verify tag matches pyproject version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "Global Hub Tag version: $TAG"
          # Check the pyproject.toml INSIDE the silo
          PY_VER=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "Silo pyproject version: $PY_VER"
          [ "$TAG" = "$PY_VER" ] || { echo "::error::Global Tag ($TAG) != Silo version ($PY_VER)"; exit 1; }

      - name: Commitizen message check
        run: |
          set -e
          git fetch --tags --force --prune
          CUR_SHA="$(git rev-parse "$GITHUB_SHA")"
          # Look for previous tags at the Hub level
          PREV_TAG="$(git describe --tags --abbrev=0 --match 'v*' "${CUR_SHA}^" 2>/dev/null || true)"

          if [ -z "$PREV_TAG" ]; then
            RANGE="${CUR_SHA}~1..${CUR_SHA}"
          else
            RANGE="${PREV_TAG}..${CUR_SHA}"
          fi

          echo "Checking commits in range: $RANGE"
          uv run cz check --rev-range "$RANGE"

      - name: Build artifacts
        run: uv build

      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: adif-mcp/dist/* # Explicit path relative to root

  publish-pypi:
    name: Publish to PyPI
    # Only publish if it's a final release (no alpha/beta/rc tags)
    if: startsWith(github.ref_name, 'v') && !contains(github.ref_name, 'a') && !contains(github.ref_name, 'b') && !contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "ADIF-MCP ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz
